In [1]:
import tensorflow as tf
from sklearn import datasets
import numpy as np
import pandas as pd

In [2]:
import numpy as np

def convertToOneHot(vector, num_classes=None):
    """
    Converts an input 1-D vector of integers into an output
    2-D array of one-hot vectors, where an i'th input value
    of j will set a '1' in the i'th row, j'th column of the
    output array.

    Example:
        v = np.array((1, 0, 4))
        one_hot_v = convertToOneHot(v)
        print one_hot_v

        [[0 1 0 0 0]
         [1 0 0 0 0]
         [0 0 0 0 1]]
    """

    assert isinstance(vector, np.ndarray)
    assert len(vector) > 0

    if num_classes is None:
        num_classes = np.max(vector)+1
    else:
        assert num_classes > 0
        assert num_classes >= np.max(vector)

    result = np.zeros(shape=(len(vector), num_classes))
    result[np.arange(len(vector)), vector] = 1
    return result.astype(int)


In [3]:
##data load
iris = datasets.load_iris()

##one hot
onehotTarget = convertToOneHot(iris.target)

## train set & test set
df = pd.DataFrame(np.random.randn(150, 2))
msk = np.random.rand(len(df)) < 0.8
train_x = iris.data[msk]
train_y = onehotTarget[msk]
test_x = iris.data[~msk]
test_y = onehotTarget[~msk]

In [5]:
##placeholder
inp = tf.placeholder(tf.float32, [None, 4],name="inp")
y_ = tf.placeholder(tf.float32, [None, 3])

##weights&bias
weights = tf.Variable(tf.zeros([4, 3]))
bias = tf.Variable(tf.zeros([3]))

##neutral arichture
y = tf.nn.softmax(tf.matmul(inp, weights) + bias)

##loss function-cross entropy
cross_entropy = -tf.reduce_sum(y_*tf.log(y))

##optimzer
train_step = tf.train.AdamOptimizer(0.01).minimize(cross_entropy)


##accuracy
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

In [6]:
for i in range(300):
    feed_train = {inp: train_x, 
                  y_: train_y}
    feed_test = {inp:test_x, 
              y_: test_y}
    
    sess.run(train_step, 
             feed_dict=feed_train)
    if i % 10 == 0:
        
        print("Train accuracy:",sess.run(accuracy,feed_dict=feed_train),
              "Test accuracy:",sess.run(accuracy,feed_dict=feed_test)
             )
        


Train Loss: 0.372727 Test Loss: 0.225
Train Loss: 0.727273 Test Loss: 0.5
Train Loss: 0.727273 Test Loss: 0.5
Train Loss: 0.727273 Test Loss: 0.5
Train Loss: 0.727273 Test Loss: 0.5
Train Loss: 0.727273 Test Loss: 0.5
Train Loss: 0.763636 Test Loss: 0.55
Train Loss: 0.790909 Test Loss: 0.575
Train Loss: 0.809091 Test Loss: 0.675
Train Loss: 0.854545 Test Loss: 0.725
Train Loss: 0.909091 Test Loss: 0.75
Train Loss: 0.918182 Test Loss: 0.75
Train Loss: 0.918182 Test Loss: 0.825
Train Loss: 0.927273 Test Loss: 0.875
Train Loss: 0.936364 Test Loss: 0.875
Train Loss: 0.954545 Test Loss: 0.9
Train Loss: 0.954545 Test Loss: 0.9
Train Loss: 0.954545 Test Loss: 0.9
Train Loss: 0.954545 Test Loss: 0.925
Train Loss: 0.954545 Test Loss: 0.925
Train Loss: 0.954545 Test Loss: 0.925
Train Loss: 0.954545 Test Loss: 0.95
Train Loss: 0.954545 Test Loss: 0.95
Train Loss: 0.954545 Test Loss: 0.95
Train Loss: 0.954545 Test Loss: 0.975
Train Loss: 0.954545 Test Loss: 0.975
Train Loss: 0.963636 Test Loss: 0.